/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DatSketch (https://sketchfab.com/DatSketch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-iphone-13-pro-max-4328dea00e47497dbeac73c556121bc9
title: Apple iPhone 13 Pro Max
*/

import React, { useRef, useLayoutEffect } from "react";
import { OrthographicCamera, useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useThree } from "@react-three/fiber";

// import SceneGLTF from "../../../public/scene.gltf";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/iphone.gltf");

  let camera = useThree((state) => state.camera);
  let scene = useThree((state) => state.scene);

  // useLayoutEffect(() => {
  //   camera.position.set(0, 2, 6);

  //   let fov = camera.fov;

  //   fov = (1400 * 18) / window.innerWidth;
  //   camera.fov = fov;
  //   camera.updateProjectionMatrix();

  //   let mm = gsap.matchMedia();

  //   mm.add(
  //     {
  //       // set up any number of arbitrarily-named conditions. The function below will be called when ANY of them match.
  //       isDesktop: `(min-width: 48em)`,
  //       isMobile: `(max-width:48em`,
  //     },
  //     (context) => {
  //       // context.conditions has a boolean property for each condition defined above indicating if it's matched or not.
  //       let { isDesktop, isMobile } = context.conditions;

  //       let t1 = gsap.timeline({
  //         scrollTrigger: {
  //           trigger: "#phone-model",
  //           start: "top+=200 top",
  //           endTrigger: "#battery",
  //           end: "top top",
  //           scrub: 1,
  //           // markers: true,
  //         },
  //       });

  //       t1.fromTo(camera.position, { y: 2 }, { y: 0 })
  //         .to(scene.rotation, { y: 0.8 })
  //         .to(scene.rotation, { y: 3 })
  //         .to(scene.rotation, { z: 1.58 }, "key1")
  //         .to(camera.position, { z: 4 }, "key1")
  //         .to(scene.rotation, { y: 0, z: 0 }, "key2")
  //         .to(camera.position, { z: 6, x: isDesktop ? -1 : 0 }, "key2")
  //         .to(scene.rotation, { z: 0, y: 6.3 }, "key3")
  //         .to(camera.position, { x: isDesktop ? 0.8 : 0, y: 0 }, "key3");

  //       if (isMobile) {
  //         camera.fov = 20;
  //         camera.updateProjectionMatrix();
  //       }

  //       return () => {
  //         if (t1) t1.kill();
  //       };
  //     }
  //   );
  // }, []);

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.3, 20.85, -4.12]}>
          <group position={[0.1, 7.83, 4.12]}>
            <group position={[-11.5, 252.79, 15.88]}>
              <group position={[11.58, -12.26, 1.28]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_2_1.geometry}
                  material={nodes.Ellipse_2_1.material}
                  position={[27.83, 0, -0.35]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_1.geometry}
                  material={nodes.Ellipse_1.material}
                  position={[27.83, 0, -0.81]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_6.geometry}
                  material={nodes.Rectangle_6.material}
                  position={[0, 0, -1.07]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_5.geometry}
                material={nodes.Rectangle_5.material}
                position={[11.5, 8.79, -0.01]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_4.geometry}
              material={nodes.Rectangle_4.material}
              position={[76.09, 137.8, 0]}
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_3.geometry}
              material={nodes.Rectangle_3.material}
              position={[-62.45, -137.8, 0]}
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_2.geometry}
              material={nodes.Rectangle_2.material}
              position={[0, -215.43, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle.geometry}
              material={nodes.Rectangle.material}
              position={[0, 210.74, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <group position={[7.82, -269.08, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse_6.geometry}
                material={nodes.Ellipse_6.material}
                position={[-35.18, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse_5.geometry}
                material={nodes.Ellipse_5.material}
                position={[59.18, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse_6_1.geometry}
                material={nodes.Ellipse_6_1.material}
                position={[-51.18, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse_4.geometry}
                material={nodes.Ellipse_4.material}
                position={[51.18, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse_3.geometry}
                material={nodes.Ellipse_3.material}
                position={[43.18, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse_6_2.geometry}
                material={nodes.Ellipse_6_2.material}
                position={[-59.18, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse_2.geometry}
                material={nodes.Ellipse_2.material}
                position={[35.18, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse.geometry}
                material={nodes.Ellipse.material}
                position={[20.18, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_2_1.geometry}
                material={nodes.Rectangle_2_1.material}
                position={[-7.82, -0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_1.geometry}
                material={nodes.Rectangle_1.material}
                position={[-7.82, 0.08, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              position={[26.33, 59.32, -14.8]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.07, 0.07, 0]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled.geometry}
                material={nodes.Untitled.material}
                position={[181, -238, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled_1.geometry}
                material={nodes.Untitled_1.material}
                position={[423, -1, 0.01]}
              />
            </group>
            <group position={[52.98, 191.1, -23.02]} scale={1.16}>
              <group
                position={[-25.87, 36.93, -1.91]}
                scale={[0.94, 0.94, 0.85]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_7.geometry}
                  material={nodes.Ellipse_7.material}
                  position={[0.13, 0.39, -2.25]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[1, 1, 1.11]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_2_2.geometry}
                  material={nodes.Ellipse_2_2.material}
                  position={[0, 0, 0.66]}
                  rotation={[-Math.PI, 0, Math.PI]}
                  scale={[0.91, 0.91, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_8.geometry}
                  material={nodes.Ellipse_8.material}
                  position={[0, 0, 0.34]}
                  rotation={[-Math.PI, 0, Math.PI]}
                  scale={[0.91, 0.91, 1]}
                />
              </group>
              <group position={[25.45, -30.01, -0.78]} scale={0.86}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_7_1.geometry}
                  material={nodes.Ellipse_7_1.material}
                  position={[0, 0, 0.93]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_6_3.geometry}
                  material={nodes.Ellipse_6_3.material}
                  position={[0, 0, 0.5]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_10.geometry}
                  material={nodes.Ellipse_10.material}
                  position={[-0.17, -0.12, -2.07]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_5_1.geometry}
                  material={nodes.Ellipse_5_1.material}
                  position={[-0.17, -0.12, 1.1]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_4_1.geometry}
                  material={nodes.Ellipse_4_1.material}
                  position={[-0.5, -0.19, 1.6]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_9.geometry}
                  material={nodes.Ellipse_9.material}
                  position={[-3.5, 2, -2.32]}
                  rotation={[-Math.PI, 0, Math.PI]}
                  scale={0.5}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_8_1.geometry}
                  material={nodes.Ellipse_8_1.material}
                  position={[1.5, -2, -2.32]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_3_2.geometry}
                  material={nodes.Ellipse_3_2.material}
                  position={[-0.5, 0, 2.5]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
              </group>
              <group position={[-25.3, -2.16, -0.78]} scale={0.86}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_7_2.geometry}
                  material={nodes.Ellipse_7_2.material}
                  position={[0, 0, 0.93]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_6_4.geometry}
                  material={nodes.Ellipse_6_4.material}
                  position={[0, 0, 0.5]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_10_1.geometry}
                  material={nodes.Ellipse_10_1.material}
                  position={[-0.17, -0.12, -2.07]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_5_2.geometry}
                  material={nodes.Ellipse_5_2.material}
                  position={[-0.17, -0.12, 1.1]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_4_2.geometry}
                  material={nodes.Ellipse_4_2.material}
                  position={[-0.5, -0.19, 1.6]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_9_1.geometry}
                  material={nodes.Ellipse_9_1.material}
                  position={[-3.5, 2, -2.32]}
                  rotation={[-Math.PI, 0, Math.PI]}
                  scale={0.5}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_8_2.geometry}
                  material={nodes.Ellipse_8_2.material}
                  position={[1.5, -2, -2.32]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_3_3.geometry}
                  material={nodes.Ellipse_3_3.material}
                  position={[-0.5, 0, 2.5]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
              </group>
              <group position={[26.18, 23.96, -0.78]} scale={0.86}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_7_3.geometry}
                  material={nodes.Ellipse_7_3.material}
                  position={[0, 0, 0.93]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_6_5.geometry}
                  material={nodes.Ellipse_6_5.material}
                  position={[0, 0, 0.5]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_10_2.geometry}
                  material={nodes.Ellipse_10_2.material}
                  position={[-0.17, -0.12, -2.07]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_5_3.geometry}
                  material={nodes.Ellipse_5_3.material}
                  position={[-0.17, -0.12, 1.1]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_4_3.geometry}
                  material={nodes.Ellipse_4_3.material}
                  position={[-0.5, -0.19, 1.6]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_9_2.geometry}
                  material={nodes.Ellipse_9_2.material}
                  position={[-3.5, 2, -2.32]}
                  rotation={[-Math.PI, 0, Math.PI]}
                  scale={0.5}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_8_3.geometry}
                  material={nodes.Ellipse_8_3.material}
                  position={[1.5, -2, -2.32]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_3_4.geometry}
                  material={nodes.Ellipse_3_4.material}
                  position={[-0.5, 0, 2.5]}
                  rotation={[-Math.PI, 0, Math.PI]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_2.geometry}
                material={nodes.Cube_2.material}
                position={[0.24, -2.53, -1.13]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={0.86}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={nodes.Cube.material}
                position={[0.24, -2.53, -1.81]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={0.86}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ellipse_3_1.geometry}
                material={nodes.Ellipse_3_1.material}
                position={[-25.87, -41.02, -1.38]}
                rotation={[-Math.PI, 0, Math.PI]}
                scale={[0.86, 0.86, 0.85]}
              />
            </group>
            <group position={[10.63, 18.95, 0.83]} scale={[1.02, 1.02, 1.04]}>
              <group
                position={[-139.66, 74.64, 0.26]}
                scale={[0.98, 0.98, 0.96]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse_11.geometry}
                  material={nodes.Ellipse_11.material}
                  position={[-0.02, -262.95, -0.09]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_9.geometry}
                  material={nodes.Rectangle_9.material}
                  position={[0.77, 61.22, -0.26]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[1.04, 1.02, 1.02]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_8.geometry}
                  material={nodes.Rectangle_8.material}
                  position={[-1.51, 61.24, 2.07]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1.04, 1.02, 1.02]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_7.geometry}
                  material={nodes.Rectangle_7.material}
                  position={[-1.51, 11.96, 0]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1.04, 1.02, 1.02]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_11.geometry}
                  material={nodes.Rectangle_11.material}
                  position={[0.24, -241.12, 0]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[1.04, 1.02, 1.02]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_10.geometry}
                  material={nodes.Rectangle_10.material}
                  position={[0.54, -241.12, 0]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[1.04, 1.02, 1.02]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_5_1.geometry}
                  material={nodes.Rectangle_5_1.material}
                  position={[-1.51, -38.91, 0]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1.04, 1.02, 1.02]}
                />
              </group>
              <group
                position={[118.57, -3.06, 0.26]}
                scale={[0.98, 0.98, 0.96]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Button.geometry}
                  material={nodes.Button.material}
                  position={[-0.25, -60.23, 0]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1.04, 1.02, 1.02]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Button_1.geometry}
                  material={nodes.Button_1.material}
                  position={[-1.53, 51.46, 0]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1.04, 1.02, 1.02]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Screen.geometry}
                material={nodes.Screen.material}
                position={[-10.45, -18.61, 14.55]}
                scale={[0.98, 0.98, 0.96]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Screen_Border.geometry}
                material={nodes.Screen_Border.material}
                position={[-10.45, -18.61, 14.39]}
                rotation={[-Math.PI, 0, Math.PI]}
                scale={[1.08, 1.08, 1.06]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Back_Side.geometry}
                material={nodes.Back_Side.material}
                position={[-10.04, -18.07, -9.56]}
                rotation={[-Math.PI, 0, Math.PI]}
                scale={[1.08, 1.08, 1.06]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Metal_Border.geometry}
                material={nodes.Metal_Border.material}
                position={[-10.45, -18.61, 13.04]}
                rotation={[-Math.PI, 0, Math.PI]}
                scale={[1.08, 1.08, 1.06]}
              />
            </group>
          </group>
        </group>
        <directionalLight
          intensity={0.75}
          decay={2}
          rotation={[-0.7, 0.65, 0.95]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[729.12, 313.61, 936.68]}
          rotation={[-0.32, 0.64, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Notes.geometry}
          material={nodes.Notes.material}
          position={[357, 89.65, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor.geometry}
          material={nodes.Floor.material}
          position={[-2.98, -299.44, 1.64]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
      </group>
    </group>
  );
}
